In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt
import plotly.graph_objs as go
import plotly.plotly as py
import scipy.stats as stats

import warnings
warnings.filterwarnings('ignore')

In [2]:
emlak = pd.read_csv('train.csv')
emlak.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [3]:
emlak.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [4]:
emlak=emlak.drop(['PoolQC','Fence','MiscFeature','Alley','FireplaceQu'],axis=1)
emlak.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(35), object(38)
memory usage: 867.0+ KB

In [5]:
emlak.dropna(inplace=True)

In [6]:
emlak.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1094 entries, 0 to 1459
Data columns (total 76 columns):
Id               1094 non-null int64
MSSubClass       1094 non-null int64
MSZoning         1094 non-null object
LotFrontage      1094 non-null float64
LotArea          1094 non-null int64
Street           1094 non-null object
LotShape         1094 non-null object
LandContour      1094 non-null object
Utilities        1094 non-null object
LotConfig        1094 non-null object
LandSlope        1094 non-null object
Neighborhood     1094 non-null object
Condition1       1094 non-null object
Condition2       1094 non-null object
BldgType         1094 non-null object
HouseStyle       1094 non-null object
OverallQual      1094 non-null int64
OverallCond      1094 non-null int64
YearBuilt        1094 non-null int64
YearRemodAdd     1094 non-null int64
RoofStyle        1094 non-null object
RoofMatl         1094 non-null object
Exterior1st      1094 non-null object
Exterior2nd      1094 non-null object
MasVnrType       1094 non-null object
MasVnrArea       1094 non-null float64
ExterQual        1094 non-null object
ExterCond        1094 non-null object
Foundation       1094 non-null object
BsmtQual         1094 non-null object
BsmtCond         1094 non-null object
BsmtExposure     1094 non-null object
BsmtFinType1     1094 non-null object
BsmtFinSF1       1094 non-null int64
BsmtFinType2     1094 non-null object
BsmtFinSF2       1094 non-null int64
BsmtUnfSF        1094 non-null int64
TotalBsmtSF      1094 non-null int64
Heating          1094 non-null object
HeatingQC        1094 non-null object
CentralAir       1094 non-null object
Electrical       1094 non-null object
1stFlrSF         1094 non-null int64
2ndFlrSF         1094 non-null int64
LowQualFinSF     1094 non-null int64
GrLivArea        1094 non-null int64
BsmtFullBath     1094 non-null int64
BsmtHalfBath     1094 non-null int64
FullBath         1094 non-null int64
HalfBath         1094 non-null int64
BedroomAbvGr     1094 non-null int64
KitchenAbvGr     1094 non-null int64
KitchenQual      1094 non-null object
TotRmsAbvGrd     1094 non-null int64
Functional       1094 non-null object
Fireplaces       1094 non-null int64
GarageType       1094 non-null object
GarageYrBlt      1094 non-null float64
GarageFinish     1094 non-null object
GarageCars       1094 non-null int64
GarageArea       1094 non-null int64
GarageQual       1094 non-null object
GarageCond       1094 non-null object
PavedDrive       1094 non-null object
WoodDeckSF       1094 non-null int64
OpenPorchSF      1094 non-null int64
EnclosedPorch    1094 non-null int64
3SsnPorch        1094 non-null int64
ScreenPorch      1094 non-null int64
PoolArea         1094 non-null int64
MiscVal          1094 non-null int64
MoSold           1094 non-null int64
YrSold           1094 non-null int64
SaleType         1094 non-null object
SaleCondition    1094 non-null object
SalePrice        1094 non-null int64
dtypes: float64(3), int64(35), object(38)
memory usage: 658.1+ KB

In [7]:
emlak.isnull().sum()*100/emlak.shape[0]

Id               0.0
MSSubClass       0.0
MSZoning         0.0
LotFrontage      0.0
LotArea          0.0
Street           0.0
LotShape         0.0
LandContour      0.0
Utilities        0.0
LotConfig        0.0
LandSlope        0.0
Neighborhood     0.0
Condition1       0.0
Condition2       0.0
BldgType         0.0
HouseStyle       0.0
OverallQual      0.0
OverallCond      0.0
YearBuilt        0.0
YearRemodAdd     0.0
RoofStyle        0.0
RoofMatl         0.0
Exterior1st      0.0
Exterior2nd      0.0
MasVnrType       0.0
MasVnrArea       0.0
ExterQual        0.0
ExterCond        0.0
Foundation       0.0
BsmtQual         0.0
                ...
BsmtFullBath     0.0
BsmtHalfBath     0.0
FullBath         0.0
HalfBath         0.0
BedroomAbvGr     0.0
KitchenAbvGr     0.0
KitchenQual      0.0
TotRmsAbvGrd     0.0
Functional       0.0
Fireplaces       0.0
GarageType       0.0
GarageYrBlt      0.0
GarageFinish     0.0
GarageCars       0.0
GarageArea       0.0
GarageQual       0.0
GarageCond       0.0
PavedDrive       0.0
WoodDeckSF       0.0
OpenPorchSF      0.0
EnclosedPorch    0.0
3SsnPorch        0.0
ScreenPorch      0.0
PoolArea         0.0
MiscVal          0.0
MoSold           0.0
YrSold           0.0
SaleType         0.0
SaleCondition    0.0
SalePrice        0.0
Length: 76, dtype: float64

In [8]:
emlak.nunique()

Id               1094
MSSubClass         15
MSZoning            5
LotFrontage       107
LotArea           806
Street              2
LotShape            4
LandContour         4
Utilities           1
LotConfig           5
LandSlope           3
Neighborhood       25
Condition1          9
Condition2          6
BldgType            5
HouseStyle          8
OverallQual         9
OverallCond         8
YearBuilt         109
YearRemodAdd       61
RoofStyle           5
RoofMatl            7
Exterior1st        14
Exterior2nd        16
MasVnrType          4
MasVnrArea        279
ExterQual           4
ExterCond           4
Foundation          5
BsmtQual            4
                 ...
BsmtFullBath        3
BsmtHalfBath        3
FullBath            4
HalfBath            3
BedroomAbvGr        7
KitchenAbvGr        3
KitchenQual         4
TotRmsAbvGrd       10
Functional          6
Fireplaces          4
GarageType          6
GarageYrBlt        97
GarageFinish        3
GarageCars          4
GarageArea        394
GarageQual          5
GarageCond          5
PavedDrive          3
WoodDeckSF        221
OpenPorchSF       176
EnclosedPorch      98
3SsnPorch          16
ScreenPorch        63
PoolArea            7
MiscVal            17
MoSold             12
YrSold              5
SaleType            9
SaleCondition       6
SalePrice         560
Length: 76, dtype: int64

In [9]:
listsurekli=list()
listkategorik=list()
for i in range(76):
    if (emlak.nunique()[i]>=10):
        listsurekli.append(emlak.nunique().index[i])
    else:
        listkategorik.append(emlak.nunique().index[i])

In [10]:
listsurekli

['Id',
 'MSSubClass',
 'LotFrontage',
 'LotArea',
 'Neighborhood',
 'YearBuilt',
 'YearRemodAdd',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'TotRmsAbvGrd',
 'GarageYrBlt',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'MiscVal',
 'MoSold',
 'SalePrice']

In [11]:
listkategorik

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'RoofStyle',
 'RoofMatl',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'Functional',
 'Fireplaces',
 'GarageType',
 'GarageFinish',
 'GarageCars',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolArea',
 'YrSold',
 'SaleType',
 'SaleCondition']

In [12]:
listesurekli=pd.DataFrame()
listekategorik=pd.DataFrame()
for a in listsurekli:
    listesurekli[a]=emlak[a]
for b in listkategorik:
    listekategorik[b]=emlak[b]

In [13]:
listesurekli.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1094 entries, 0 to 1459
Data columns (total 29 columns):
Id               1094 non-null int64
MSSubClass       1094 non-null int64
LotFrontage      1094 non-null float64
LotArea          1094 non-null int64
Neighborhood     1094 non-null object
YearBuilt        1094 non-null int64
YearRemodAdd     1094 non-null int64
Exterior1st      1094 non-null object
Exterior2nd      1094 non-null object
MasVnrArea       1094 non-null float64
BsmtFinSF1       1094 non-null int64
BsmtFinSF2       1094 non-null int64
BsmtUnfSF        1094 non-null int64
TotalBsmtSF      1094 non-null int64
1stFlrSF         1094 non-null int64
2ndFlrSF         1094 non-null int64
LowQualFinSF     1094 non-null int64
GrLivArea        1094 non-null int64
TotRmsAbvGrd     1094 non-null int64
GarageYrBlt      1094 non-null float64
GarageArea       1094 non-null int64
WoodDeckSF       1094 non-null int64
OpenPorchSF      1094 non-null int64
EnclosedPorch    1094 non-null int64
3SsnPorch        1094 non-null int64
ScreenPorch      1094 non-null int64
MiscVal          1094 non-null int64
MoSold           1094 non-null int64
SalePrice        1094 non-null int64
dtypes: float64(3), int64(23), object(3)
memory usage: 256.4+ KB

In [14]:
listesurekli=listesurekli.drop(['Neighborhood','Exterior1st','Exterior2nd'],axis=1)

In [15]:
listekategorik['Neighborhood']=emlak['Neighborhood']
listekategorik['Exterior1st']=emlak['Exterior1st']
listekategorik['Exterior2nd']=emlak['Exterior2nd']

## SÃ¼rekli de Ã¶zellik mÃ¼hendisliÄŸi iÃ§in;

In [16]:
listesurekli.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1094 entries, 0 to 1459
Data columns (total 26 columns):
Id               1094 non-null int64
MSSubClass       1094 non-null int64
LotFrontage      1094 non-null float64
LotArea          1094 non-null int64
YearBuilt        1094 non-null int64
YearRemodAdd     1094 non-null int64
MasVnrArea       1094 non-null float64
BsmtFinSF1       1094 non-null int64
BsmtFinSF2       1094 non-null int64
BsmtUnfSF        1094 non-null int64
TotalBsmtSF      1094 non-null int64
1stFlrSF         1094 non-null int64
2ndFlrSF         1094 non-null int64
LowQualFinSF     1094 non-null int64
GrLivArea        1094 non-null int64
TotRmsAbvGrd     1094 non-null int64
GarageYrBlt      1094 non-null float64
GarageArea       1094 non-null int64
WoodDeckSF       1094 non-null int64
OpenPorchSF      1094 non-null int64
EnclosedPorch    1094 non-null int64
3SsnPorch        1094 non-null int64
ScreenPorch      1094 non-null int64
MiscVal          1094 non-null int64
MoSold           1094 non-null int64
SalePrice        1094 non-null int64
dtypes: float64(3), int64(23)
memory usage: 230.8 KB

In [17]:
def datauret(attribute,emlak):
    y0 = emlak[attribute]
    trace0 = go.Box(
        y=y0,
        name = attribute,
        )
    return trace0

In [18]:
data_surekli=list()
rate=listesurekli
for i in range(len(rate.columns)):
    data_surekli.append(datauret(rate.columns[i],emlak))

In [19]:
def visibleTF(number):
    liste=list()
    for i in range(len(data_surekli)):
        liste.append(False)
    liste[number]=True
    return liste

In [20]:
def button(attribute,number):
    return dict(label = attribute,method = 'update',args = [{'visible': visibleTF(number)},{'title': 'Attrition iliÅŸkisi'}])

In [21]:
layout = go.Layout(
    #barmode='box',
    width=800,
    height=500,
    autosize=False,
    #margin=dict(t=0, b=0, l=0, r=0),
    title='Attrition-SÃ¼rekli Ã–zellik Box GrafiÄŸi',
    xaxis=go.layout.XAxis(
        title=go.layout.xaxis.Title(
            #text='x Axis',
            font=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        )
    ),
    yaxis=go.layout.YAxis(
        title=go.layout.yaxis.Title(
            #text='y Axis',
            font=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        )
    )
)
rate=listesurekli
updatemenus = list([dict(active=-1,buttons=[button(rate.columns[i],i) for i in range(len(rate.columns))])])

In [22]:
layout['updatemenus']=updatemenus
fig = dict(data=data_surekli, layout=layout)
py.iplot(fig, filename='a')

In [23]:
def datauret(attribute,emlak):
    
    y0 = emlak[attribute]
    y1 = np.log(emlak[attribute])
    #y2 = winsorize(employee[attribute], (0, 0.05))
    log=attribute+'_log'
    #wins=attribute+'_wins'
    emlak[log]=np.log(emlak[attribute])
    #employee[wins]=winsorize(employee[attribute], (0, 0.05))
    
    trace = go.Box(
        y=y0,
        name = attribute,
        marker = dict(
            color = 'rgb(214, 12, 140)',
        )
    )
    trace1 = go.Box(
        y=y1,
        name = attribute+'_log',
        marker = dict(
            color = 'rgb(0, 128, 128)',
        )
    )
    trace2 = go.Box(
        y=y0,
        name = attribute+'_winsorize',
        boxpoints = False,
        marker = dict(
            color = 'rgb(214, 12, 0)',
        )
    )

    data = [trace, trace1]
    return data

In [24]:
data_surekli=list()
rate=listesurekli[['MSSubClass','LotFrontage','LotArea','MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF',
                  '1stFlrSF','2ndFlrSF','LowQualFinSF','GrLivArea','TotRmsAbvGrd','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch',
                  'ScreenPorch','MiscVal','SalePrice']]
for i in range(len(rate.columns)):
    for j in range(2):
        data_surekli.append(datauret(rate.columns[i],emlak)[j])

In [25]:
from plotly import tools
fig = tools.make_subplots(rows=21, cols=2)

for i in range(21*2):
    if(i<2):
        fig.append_trace(data_surekli[i], 1, i+1)
    elif(i<4):
        fig.append_trace(data_surekli[i], 2, i-1)
    elif(i<6):
        fig.append_trace(data_surekli[i], 3, i-3)
    elif(i<8):
        fig.append_trace(data_surekli[i], 4, i-5)
    elif(i<10):
        fig.append_trace(data_surekli[i], 5, i-7)
    elif(i<12):
        fig.append_trace(data_surekli[i], 6, i-9)
    elif(i<14):
        fig.append_trace(data_surekli[i], 7, i-11)
    elif(i<16):
        fig.append_trace(data_surekli[i], 8, i-13)
    elif(i<18):
        fig.append_trace(data_surekli[i], 9, i-15)
    elif(i<20):
        fig.append_trace(data_surekli[i], 10, i-17)
    elif(i<22):
        fig.append_trace(data_surekli[i], 11, i-19)
    elif(i<24):
        fig.append_trace(data_surekli[i], 12, i-21)
    elif(i<26):
        fig.append_trace(data_surekli[i], 13, i-23)
    elif(i<28):
        fig.append_trace(data_surekli[i], 14, i-25)
    elif(i<30):
        fig.append_trace(data_surekli[i], 15, i-27) 
    elif(i<32):
        fig.append_trace(data_surekli[i], 16, i-29) 
    elif(i<34):
        fig.append_trace(data_surekli[i], 17, i-31) 
    elif(i<36):
        fig.append_trace(data_surekli[i], 18, i-33) 
    elif(i<38):
        fig.append_trace(data_surekli[i], 19, i-35)
    elif(i<40):
        fig.append_trace(data_surekli[i], 20, i-37)
    else:
        fig.append_trace(data_surekli[i], 21, i-39)
        
fig['layout'].update(height=3000, width=1000, title='AÅŸÄ±rÄ± deÄŸerler iÃ§in log-winsorize grafikleri')
py.iplot(fig, filename='simple-subplot-with-annotations')

This is the format of your plot grid:
[ (1,1) x1,y1 ]     [ (1,2) x2,y2 ]
[ (2,1) x3,y3 ]     [ (2,2) x4,y4 ]
[ (3,1) x5,y5 ]     [ (3,2) x6,y6 ]
[ (4,1) x7,y7 ]     [ (4,2) x8,y8 ]
[ (5,1) x9,y9 ]     [ (5,2) x10,y10 ]
[ (6,1) x11,y11 ]   [ (6,2) x12,y12 ]
[ (7,1) x13,y13 ]   [ (7,2) x14,y14 ]
[ (8,1) x15,y15 ]   [ (8,2) x16,y16 ]
[ (9,1) x17,y17 ]   [ (9,2) x18,y18 ]
[ (10,1) x19,y19 ]  [ (10,2) x20,y20 ]
[ (11,1) x21,y21 ]  [ (11,2) x22,y22 ]
[ (12,1) x23,y23 ]  [ (12,2) x24,y24 ]
[ (13,1) x25,y25 ]  [ (13,2) x26,y26 ]
[ (14,1) x27,y27 ]  [ (14,2) x28,y28 ]
[ (15,1) x29,y29 ]  [ (15,2) x30,y30 ]
[ (16,1) x31,y31 ]  [ (16,2) x32,y32 ]
[ (17,1) x33,y33 ]  [ (17,2) x34,y34 ]
[ (18,1) x35,y35 ]  [ (18,2) x36,y36 ]
[ (19,1) x37,y37 ]  [ (19,2) x38,y38 ]
[ (20,1) x39,y39 ]  [ (20,2) x40,y40 ]
[ (21,1) x41,y41 ]  [ (21,2) x42,y42 ]

In [26]:
import math
def definite(a,emlak):
    mediann=emlak[(emlak[a]!=-math.inf)|(emlak[a]!=math.inf)][a].median()
    inf=emlak[(emlak[a]==-math.inf)|(emlak[a]==math.inf)][a]
    for i in range(len(inf.index)):
        emlak.loc[inf.index[i],a]=mediann
    return emlak[a]

In [27]:
rate=emlak[['MSSubClass_log','LotFrontage_log','LotArea_log','MasVnrArea_log','BsmtFinSF1_log','BsmtFinSF2_log','BsmtUnfSF_log','TotalBsmtSF_log',
                  '1stFlrSF_log','2ndFlrSF_log','LowQualFinSF_log','GrLivArea_log','TotRmsAbvGrd_log','GarageArea_log','WoodDeckSF_log','OpenPorchSF_log','EnclosedPorch_log','3SsnPorch_log',
                  'ScreenPorch_log','MiscVal_log','SalePrice_log']]
for i in rate.columns:
    emlak[i]=definite(i,emlak)
    listesurekli[i]=emlak[i]

In [28]:
listesurekli=listesurekli.drop(['MSSubClass','LotFrontage','LotArea','MasVnrArea','BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF',
                  '1stFlrSF','2ndFlrSF','LowQualFinSF','GrLivArea','TotRmsAbvGrd','GarageArea','WoodDeckSF','OpenPorchSF','EnclosedPorch','3SsnPorch',
                  'ScreenPorch','MiscVal'],axis=1)

In [29]:
listesurekli.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1094 entries, 0 to 1459
Data columns (total 27 columns):
Id                   1094 non-null int64
YearBuilt            1094 non-null int64
YearRemodAdd         1094 non-null int64
GarageYrBlt          1094 non-null float64
MoSold               1094 non-null int64
SalePrice            1094 non-null int64
MSSubClass_log       1094 non-null float64
LotFrontage_log      1094 non-null float64
LotArea_log          1094 non-null float64
MasVnrArea_log       1094 non-null float64
BsmtFinSF1_log       1094 non-null float64
BsmtFinSF2_log       1094 non-null float64
BsmtUnfSF_log        1094 non-null float64
TotalBsmtSF_log      1094 non-null float64
1stFlrSF_log         1094 non-null float64
2ndFlrSF_log         1094 non-null float64
LowQualFinSF_log     1094 non-null float64
GrLivArea_log        1094 non-null float64
TotRmsAbvGrd_log     1094 non-null float64
GarageArea_log       1094 non-null float64
WoodDeckSF_log       1094 non-null float64
OpenPorchSF_log      1094 non-null float64
EnclosedPorch_log    1094 non-null float64
3SsnPorch_log        1094 non-null float64
ScreenPorch_log      1094 non-null float64
MiscVal_log          1094 non-null float64
SalePrice_log        1094 non-null float64
dtypes: float64(22), int64(5)
memory usage: 239.3 KB

In [30]:
listesurekli.corr()

,Id,YearBuilt,YearRemodAdd,GarageYrBlt,MoSold,SalePrice,MSSubClass_log,LotFrontage_log,LotArea_log,MasVnrArea_log,...,GrLivArea_log,TotRmsAbvGrd_log,GarageArea_log,WoodDeckSF_log,OpenPorchSF_log,EnclosedPorch_log,3SsnPorch_log,ScreenPorch_log,MiscVal_log,SalePrice_log
Id,1.000000,-0.022610,-0.030239,-0.003820,0.007486,-0.047595,0.015339,-0.018819,-0.030421,-0.115614,...,-0.015279,0.009784,-0.029108,0.027916,-0.015180,0.174172,-0.366650,-0.092061,0.318634,-0.041486
YearBuilt,-0.022610,1.000000,0.625905,0.824156,0.014127,0.523434,-0.026673,0.072809,0.028644,0.038632,...,0.236692,0.130506,0.514664,0.093004,0.264933,0.078124,0.006287,0.125138,-0.129601,0.593347
YearRemodAdd,-0.030239,0.625905,1.000000,0.648282,0.031242,0.519806,0.007610,0.057908,0.054108,-0.008136,...,0.313773,0.186004,0.430844,0.098490,0.267130,0.021471,-0.176908,0.015144,0.288813,0.591800
GarageYrBlt,-0.003820,0.824156,0.648282,1.000000,0.011159,0.502248,0.021615,0.042585,0.025683,0.030096,...,0.266064,0.170711,0.649456,0.074285,0.274869,0.100002,-0.010923,0.166499,-0.018730,0.561098
MoSold,0.007486,0.014127,0.031242,0.011159,1.000000,0.052584,0.002179,0.028790,0.019141,0.034976,...,0.069140,0.047463,0.035990,-0.036551,0.103217,-0.088775,-0.177824,-0.019030,0.143036,0.063051
SalePrice,-0.047595,0.523434,0.519806,0.502248,0.052584,1.000000,-0.040523,0.343311,0.405807,0.370827,...,0.695413,0.544085,0.594137,0.243394,0.367067,0.122867,0.102861,0.258493,0.518861,0.952834
MSSubClass_log,0.015339,-0.026673,0.007610,0.021615,0.002179,-0.040523,1.000000,-0.433344,-0.398166,0.025211,...,0.208796,0.141971,-0.065988,-0.088592,0.014931,0.061944,-0.091148,-0.021302,0.297071,-0.034735
LotFrontage_log,-0.018819,0.072809,0.057908,0.042585,0.028790,0.343311,-0.433344,1.000000,0.741485,0.177442,...,0.336111,0.361009,0.327084,0.168302,0.158472,0.311674,0.341035,0.155537,-0.061811,0.364504
LotArea_log,-0.030421,0.028644,0.054108,0.025683,0.019141,0.405807,-0.398166,0.741485,1.000000,0.223511,...,0.382350,0.382264,0.312015,0.231289,0.163697,0.228203,0.218678,0.185562,0.216545,0.410481
MasVnrArea_log,-0.115614,0.038632,-0.008136,0.030096,0.034976,0.370827,0.025211,0.177442,0.223511,1.000000,...,0.411743,0.324574,0.307624,0.313935,0.174516,-0.087005,0.439465,0.208925,-0.086685,0.335768
BsmtFinSF1_log,0.007495,0.074978,0.015322,0.047052,-0.002028,0.240115,-0.059376,0.128577,0.199451,0.231729,...,0.125339,0.069673,0.167014,0.164413,0.081505,0.034146,0.554980,-0.030821,0.165982,0.216161
BsmtFinSF2_log,0.069843,0.045514,0.088883,0.022043,0.054451,0.152259,-0.115529,0.079473,0.130579,-0.092355,...,0.110527,0.101499,0.018798,-0.086133,0.114949,0.062199,NaN,0.334282,0.486621,0.158270
BsmtUnfSF_log,-0.024464,0.052242,0.073835,0.098800,-0.008970,0.082319,-0.113769,0.105667,0.056543,-0.051947,...,0.185617,0.191735,0.118523,-0.083884,0.066694,-0.040820,-0.179811,0.205767,-0.008635,0.085443
TotalBsmtSF_log,-0.032231,0.436876,0.287083,0.360242,0.003843,0.603194,-0.343771,0.371111,0.388694,0.183798,...,0.430032,0.306641,0.497476,0.185015,0.263638,0.194868,0.026682,0.223635,0.368902,0.621003
1stFlrSF_log,-0.007819,0.302150,0.276965,0.272890,0.037444,0.603926,-0.336451,0.456395,0.468376,0.149864,...,0.533966,0.404602,0.499457,0.251423,0.213111,0.154649,0.032953,0.153653,0.121997,0.626184
2ndFlrSF_log,-0.059624,0.346758,0.370668,0.321579,0.062663,0.631218,-0.031893,0.391069,0.389396,0.326491,...,0.800747,0.644505,0.516999,0.216345,0.301943,0.195657,-0.394463,0.414880,0.107779,0.676608
LowQualFinSF_log,-0.380317,-0.672664,-0.450539,-0.304396,-0.253788,0.352286,-0.483862,0.591968,0.641061,NaN,...,0.580992,0.699324,0.210066,0.792726,-0.284131,0.078104,NaN,NaN,-1.000000,0.318605
GrLivArea_log,-0.015279,0.236692,0.313773,0.266064,0.069140,0.695413,0.208796,0.336111,0.382350,0.411743,...,1.000000,0.831881,0.468298,0.216960,0.338645,0.219936,0.153172,0.263096,0.416196,0.727793
TotRmsAbvGrd_log,0.009784,0.130506,0.186004,0.170711,0.047463,0.544085,0.141971,0.361009,0.382264,0.324574,...,0.831881,1.000000,0.361588,0.108907,0.242007,0.145176,-0.074278,0.187407,0.482542,0.562521
GarageArea_log,-0.029108,0.514664,0.430844,0.649456,0.035990,0.594137,-0.065988,0.327084,0.312015,0.307624,...,0.468298,0.361588,1.000000,0.194173,0.302061,0.179179,0.321379,0.250239,-0.113512,0.625750
WoodDeckSF_log,0.027916,0.093004,0.098490,0.074285,-0.036551,0.243394,-0.088592,0.168302,0.231289,0.313935,...,0.216960,0.108907,0.194173,1.000000,0.096764,-0.021675,-0.272386,-0.060064,0.073658,0.266511
OpenPorchSF_log,-0.015180,0.264933,0.267130,0.274869,0.103217,0.367067,0.014931,0.158472,0.163697,0.174516,...,0.338645,0.242007,0.302061,0.096764,1.000000,0.129595,0.036484,0.267839,0.186235,0.385368
EnclosedPorch_log,0.174172,0.078124,0.021471,0.100002,-0.088775,0.122867,0.061944,0.311674,0.228203,-0.087005,...,0.219936,0.145176,0.179179,-0.021675,0.129595,1.000000,NaN,-0.136526,0.149731,0.160246
3SsnPorch_log,-0.366650,0.006287,-0.176908,-0.010923,-0.177824,0.102861,-0.091148,0.341035,0.218678,0.439465,...,0.153172,-0.074278,0.321379,-0.272386,0.036484,NaN,1.000000,NaN,NaN,0.094421
ScreenPorch_log,-0.092061,0.125138,0.015144,0.166499,-0.019030,0.258493,-0.021302,0.155537,0.185562,0.208925,...,0.263096,0.187407,0.250239,-0.060064,0.267839,-0.136526,NaN,1.000000,0.465099,0.305811
MiscVal_log,0.318634,-0.129601,0.288813,-0.018730,0.143036,0.518861,0.297071,-0.061811,0.216545,-0.086685,...,0.416196,0.482542,-0.113512,0.073658,0.186235,0.149731,NaN,0.465099,1.000000,0.552699
SalePrice_log,-0.041486,0.593347,0.591800,0.561098,0.063051,0.952834,-0.034735,0.364504,0.410481,0.335768,...,0.727793,0.562521,0.625750,0.266511,0.385368,0.160246,0.094421,0.305811,0.552699,1.000000

In [31]:
listesurekli.corr()[['SalePrice_log']]

                   SalePrice_log
Id                     -0.041486
YearBuilt               0.593347
YearRemodAdd            0.591800
GarageYrBlt             0.561098
MoSold                  0.063051
SalePrice               0.952834
MSSubClass_log         -0.034735
LotFrontage_log         0.364504
LotArea_log             0.410481
MasVnrArea_log          0.335768
BsmtFinSF1_log          0.216161
BsmtFinSF2_log          0.158270
BsmtUnfSF_log           0.085443
TotalBsmtSF_log         0.621003
1stFlrSF_log            0.626184
2ndFlrSF_log            0.676608
LowQualFinSF_log        0.318605
GrLivArea_log           0.727793
TotRmsAbvGrd_log        0.562521
GarageArea_log          0.625750
WoodDeckSF_log          0.266511
OpenPorchSF_log         0.385368
EnclosedPorch_log       0.160246
3SsnPorch_log           0.094421
ScreenPorch_log         0.305811
MiscVal_log             0.552699
SalePrice_log           1.000000

SalePrice ile aralarÄ±ndaki iliÅŸkiye baktÄ±ÄŸÄ±mÄ±zda ;
* YearBuilt        
* YearRemodAdd 
* GarageYrBlt
* TotalBsmtSF_log  
* 1stFlrSF_log 
* 2ndFlrSF_log
* GrLivArea_log        
* TotRmsAbvGrd_log     
* GarageArea_log     
* MiscVal_log

## Kategorik te Ã¶zellik mÃ¼hendisliÄŸi iÃ§in;

In [32]:
listekategorik=listekategorik.drop(['Utilities'],axis=1)

In [33]:
import plotly.graph_objs as go
import plotly.plotly as py
import scipy.stats as stats

def datauret(attribute,emlak):
    y0 = emlak.groupby(attribute)["SalePrice"].mean()
    x0 = emlak.groupby(attribute)["SalePrice"].mean().index
    trace0 = go.Bar(
        x=x0,
        y=y0,
        name = attribute,
        )
    return trace0

In [34]:
data_kategorik=list()
rate=listekategorik
for i in range(len(rate.columns)):
    data_kategorik.append(datauret(rate.columns[i],emlak))

In [35]:
def visibleTF(number):
    liste=list()
    for i in range(len(data_kategorik)):
        liste.append(False)
    liste[number]=True
    return liste

In [36]:
def button(attribute,number):
    return dict(label = attribute,method = 'update',args = [{'visible': visibleTF(number)},{'title': 'emlak iliÅŸkisi'}])

In [37]:
layout = go.Layout(
    #barmode='box',
    width=800,
    height=500,
    autosize=False,
    #margin=dict(t=0, b=0, l=0, r=0),
    title='Ã¼cret-kategorik Ã–zellik Box GrafiÄŸi',
    xaxis=go.layout.XAxis(
        title=go.layout.xaxis.Title(
            #text='x Axis',
            font=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        )
    ),
    yaxis=go.layout.YAxis(
        title=go.layout.yaxis.Title(
            #text='y Axis',
            font=dict(
                family='Courier New, monospace',
                size=18,
                color='#7f7f7f'
            )
        )
    )
)
rate=listekategorik
updatemenus = list([dict(active=-1,buttons=[button(rate.columns[i],i) for i in range(len(rate.columns))])])

In [38]:
layout['updatemenus']=updatemenus
fig = dict(data=data_kategorik, layout=layout)
py.iplot(fig, filename='a')

In [39]:
for a in listekategorik.columns:
    MsZoningler = emlak[a].unique()
    pd.options.display.float_format = '{:.15f}'.format
    for var in ['SalePrice']:
        karsilastirma = pd.DataFrame(columns=['grup_1', 'grup_2','istatistik', 'p_degeri'])
        print("{} iÃ§in karÅŸÄ±laÅŸtÄ±rma".format(var),end='')
        print("---"+a)
        for i in range(0, len(MsZoningler)):
            for j in range(i+1, len(MsZoningler)):
                ttest = stats.ttest_ind(emlak[emlak[a]==MsZoningler[i]][var], 
                                    emlak[emlak[a]==MsZoningler[j]][var])
                grup_1 = MsZoningler[i]
                grup_2 = MsZoningler[j]
                istatistik = ttest[0]
                p_degeri = ttest[1]
            
                karsilastirma = karsilastirma.append({"grup_1" : grup_1 ,
                                                      "grup_2" : grup_2 ,
                                                      "istatistik": istatistik , 
                                                      "p_degeri" : p_degeri}, ignore_index=True)
        display(karsilastirma)

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---MSZoning

    grup_1   grup_2          istatistik          p_degeri
0       RL       RM  10.087798023247766 0.000000000000000
1       RL  C (all)   3.997408122514001 0.000069561970604
2       RL       FV  -1.779874847151598 0.075433036519384
3       RL       RH   2.506065358570652 0.012392607464271
4       RM  C (all)   2.886024065883071 0.004381488211850
5       RM       FV -10.890545100509158 0.000000000000000
6       RM       RH   0.205534075012061 0.837387138431150
7  C (all)       FV  -6.984787386464858 0.000000002655528
8  C (all)       RH  -2.884394013694352 0.011348064627954
9       FV       RH   4.808951914592059 0.000010314860502

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Street

  grup_1 grup_2        istatistik          p_degeri
0   Pave   Grvl 1.896164352625761 0.058202082686248

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---LotShape

  grup_1 grup_2          istatistik          p_degeri
0    Reg    IR1 -10.660657108531106 0.000000000000000
1    Reg    IR2  -5.783434025595262 0.000000010570192
2    Reg    IR3  -2.229843450597685 0.026047298323580
3    IR1    IR2  -1.375489258126809 0.169927097268796
4    IR1    IR3  -0.091661652549557 0.927026841753489
5    IR2    IR3   0.484345167282895 0.631545444880932

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---LandContour

  grup_1 grup_2         istatistik          p_degeri
0    Lvl    Bnk  3.269635054608364 0.001112382642348
1    Lvl    Low -1.361071582138896 0.173796779855544
2    Lvl    HLS -4.134452392716411 0.000038466071510
3    Bnk    Low -3.586430468877492 0.000696466082500
4    Bnk    HLS -5.412310122500394 0.000000542437508
5    Low    HLS -0.718398655723482 0.475498279571689

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---LotConfig

    grup_1   grup_2         istatistik          p_degeri
0   Inside      FR2 -0.365304657012421 0.714974140399571
1   Inside   Corner -0.578708654638201 0.562914164635786
2   Inside  CulDSac -6.805437151636194 0.000000000018721
3   Inside      FR3 -0.660848866127557 0.508892179015806
4      FR2   Corner  0.087066286837811 0.930700235742713
5      FR2  CulDSac -3.390396013245779 0.001143117419196
6      FR2      FR3 -0.547726363940458 0.587802229646044
7   Corner  CulDSac -4.952760659072546 0.000001420629403
8   Corner      FR3 -0.469403412946412 0.639322376753124
9  CulDSac      FR3  1.016527478803638 0.314695239682439

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---LandSlope

  grup_1 grup_2         istatistik          p_degeri
0    Gtl    Mod -1.123906577439345 0.261300801331549
1    Gtl    Sev -0.383890089323719 0.701137782164898
2    Mod    Sev  0.003513056142994 0.997211861542840

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Condition1

    grup_1  grup_2         istatistik          p_degeri
0     Norm   Feedr  3.616933823478732 0.000313010619107
1     Norm  Artery  3.950536622818614 0.000083506773101
2     Norm    RRAe  1.751065319137986 0.080255362737166
3     Norm    RRNn -0.488904731080341 0.625021755377159
4     Norm    RRAn  0.327458602738105 0.743391560613605
5     Norm    PosN -0.664868556151166 0.506294750096248
6     Norm    PosA -1.130899534276077 0.258382192724084
7     Norm    RRNe                nan               nan
8    Feedr  Artery  0.845648383149655 0.399942976454635
9    Feedr    RRAe  0.673680323434573 0.503190521209465
10   Feedr    RRNn -2.653094276021907 0.010452337076556
11   Feedr    RRAn -2.974682684839248 0.003958723049468
12   Feedr    PosN -3.575416606450197 0.000705401092111
13   Feedr    PosA -4.193379730105229 0.000102761860958
14   Feedr    RRNe                nan               nan
15  Artery    RRAe  0.003011475240444 0.997609675288184
16  Artery    RRNn -1.919090409292033 0.061473536111762
17  Artery    RRAn -2.634434080764705 0.010557777225866
18  Artery    PosN -2.699633705344778 0.009500471229251
19  Artery    PosA -2.760008166287591 0.008394411530874
20  Artery    RRNe                nan               nan
21    RRAe    RRNn -1.915064500763339 0.084495221099866
22    RRAe    RRAn -1.871035170209923 0.071122486757419
23    RRAe    PosN -2.352096828469381 0.032744416854899
24    RRAe    PosA -3.875794392139623 0.003079952892930
25    RRAe    RRNe                nan               nan
26    RRNn    RRAn  0.659695830818151 0.515250672722124
27    RRNn    PosN  0.035278593531568 0.972489644927205
28    RRNn    PosA -0.425423289257927 0.685364225469485
29    RRNn    RRNe                nan               nan
30    RRAn    PosN -0.866636367079299 0.392799832241021
31    RRAn    PosA -1.447928032187249 0.159589415904460
32    RRAn    RRNe                nan               nan
33    PosN    PosA -0.614022116405012 0.551687945176314
34    PosN    RRNe                nan               nan
35    PosA    RRNe                nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Condition2

    grup_1  grup_2         istatistik          p_degeri
0     Norm  Artery  1.376081909150397 0.169081014154918
1     Norm    RRNn  1.541969768503279 0.123373336051119
2     Norm   Feedr  1.585739974624880 0.113089690478685
3     Norm    PosN -1.659134607379204 0.097378473355564
4     Norm    PosA                nan               nan
5   Artery    RRNn  0.319661392904331 0.779527266975079
6   Artery   Feedr -0.890385160546532 0.414044508780690
7   Artery    PosN -1.769887170441731 0.218766106125962
8   Artery    PosA                nan               nan
9     RRNn   Feedr -1.125063217246413 0.311650549569841
10    RRNn    PosN -1.808302639664114 0.212287891726330
11    RRNn    PosA                nan               nan
12   Feedr    PosN -2.693467745877859 0.043119455201484
13   Feedr    PosA                nan               nan
14    PosN    PosA                nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---BldgType

   grup_1  grup_2         istatistik          p_degeri
0    1Fam  2fmCon  3.434425259017412 0.000619680029599
1    1Fam  TwnhsE  0.330577417986412 0.741032065090103
2    1Fam  Duplex  2.636936742870759 0.008502861506386
3    1Fam   Twnhs  3.530326205647893 0.000434800586141
4  2fmCon  TwnhsE -4.344937073064970 0.000031595132273
5  2fmCon  Duplex -2.632724421908487 0.011801783594319
6  2fmCon   Twnhs -1.481222864237767 0.144468275185772
7  TwnhsE  Duplex  3.251972283453488 0.001514627974457
8  TwnhsE   Twnhs  4.186217252858708 0.000053567142023
9  Duplex   Twnhs  0.561410545294602 0.576718409402046

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---HouseStyle

    grup_1  grup_2         istatistik          p_degeri
0   2Story  1Story  5.101956916690768 0.000000411503169
1   2Story  1.5Fin  7.824712454785115 0.000000000000035
2   2Story  1.5Unf  3.422562764937467 0.000692943890847
3   2Story    SLvl  3.648209079763917 0.000300250170469
4   2Story  2.5Unf  1.899876868272050 0.058263992109412
5   2Story  2.5Fin -0.722216472418170 0.470643649866164
6   2Story  SFoyer  3.959938975180464 0.000090055755246
7   1Story  1.5Fin  5.430523755177149 0.000000079260918
8   1Story  1.5Unf  2.891357755045130 0.003988009056313
9   1Story    SLvl  1.899113334386249 0.058044639115995
10  1Story  2.5Unf  1.140001080926113 0.254784773889888
11  1Story  2.5Fin -1.781455304749921 0.075395903739921
12  1Story  SFoyer  2.917421691291769 0.003670738246102
13  1.5Fin  1.5Unf  2.026236379916106 0.044868715242728
14  1.5Fin    SLvl -2.220164840036152 0.027830917151053
15  1.5Fin  2.5Unf -0.643473605929814 0.521105108802720
16  1.5Fin  2.5Fin -4.427207456733543 0.000021051565550
17  1.5Fin  SFoyer  0.676463578713159 0.499878588249199
18  1.5Unf    SLvl -3.854346062193547 0.000326236721364
19  1.5Unf  2.5Unf -1.875398654624441 0.078020812185058
20  1.5Unf  2.5Fin -3.246801946480136 0.005849802529287
21  1.5Unf  SFoyer -2.680302999966540 0.011673622345043
22    SLvl  2.5Unf  0.432555063391964 0.667198060775725
23    SLvl  2.5Fin -3.365789033799657 0.001528524122320
24    SLvl  SFoyer  2.797732677070925 0.006790680691803
25  2.5Unf  2.5Fin -1.763915660559546 0.101216546390847
26  2.5Unf  SFoyer  1.117920873568232 0.272473438934964
27  2.5Fin  SFoyer  3.923928109224701 0.000541047176291

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---OverallQual

               grup_1             grup_2          istatistik          p_degeri
0   7.000000000000000  6.000000000000000  14.081330379778789 0.000000000000000
1   7.000000000000000  8.000000000000000 -12.954446138441554 0.000000000000000
2   7.000000000000000  5.000000000000000  23.822057216137054 0.000000000000000
3   7.000000000000000  9.000000000000000 -18.656788295691410 0.000000000000000
4   7.000000000000000  4.000000000000000  16.955884439817677 0.000000000000000
5   7.000000000000000 10.000000000000000 -14.858916725075094 0.000000000000000
6   7.000000000000000  3.000000000000000   6.758559313803040 0.000000000088338
7   7.000000000000000  2.000000000000000   4.948999988078284 0.000001344888285
8   6.000000000000000  8.000000000000000 -25.082410404708217 0.000000000000000
9   6.000000000000000  5.000000000000000  10.001180060582874 0.000000000000000
10  6.000000000000000  9.000000000000000 -29.300464033124619 0.000000000000000
11  6.000000000000000  4.000000000000000  11.217805549134223 0.000000000000000
12  6.000000000000000 10.000000000000000 -21.088796964717353 0.000000000000000
13  6.000000000000000  3.000000000000000   5.024435546825266 0.000000908492854
14  6.000000000000000  2.000000000000000   4.628809489256523 0.000005718137505
15  8.000000000000000  5.000000000000000  33.794103433144286 0.000000000000000
16  8.000000000000000  9.000000000000000  -7.524166640188981 0.000000000002488
17  8.000000000000000  4.000000000000000  21.085346886040696 0.000000000000000
18  8.000000000000000 10.000000000000000  -7.384892535192827 0.000000000009177
19  8.000000000000000  3.000000000000000   8.025352183135370 0.000000000000314
20  8.000000000000000  2.000000000000000   5.143126494496707 0.000000900975853
21  5.000000000000000  9.000000000000000 -37.881782185805577 0.000000000000000
22  5.000000000000000  4.000000000000000   6.862056605553247 0.000000000030226
23  5.000000000000000 10.000000000000000 -25.931707959102436 0.000000000000000
24  5.000000000000000  3.000000000000000   3.767199639424951 0.000198939970637
25  5.000000000000000  2.000000000000000   4.623247648351953 0.000005679671384
26  9.000000000000000  4.000000000000000  24.366392824380068 0.000000000000000
27  9.000000000000000 10.000000000000000  -2.011276803949125 0.049118751797911
28  9.000000000000000  3.000000000000000   9.228663655974861 0.000000000003277
29  9.000000000000000  2.000000000000000   5.486657777252098 0.000002166225256
30  4.000000000000000 10.000000000000000 -15.314934862531420 0.000000000000000
31  4.000000000000000  3.000000000000000   1.303687837288929 0.196493102821728
32  4.000000000000000  2.000000000000000   3.735750262911391 0.000392811024987
33 10.000000000000000  3.000000000000000   5.533322991120873 0.000014634027928
34 10.000000000000000  2.000000000000000   3.142175851971939 0.006297735898608
35  3.000000000000000  2.000000000000000   2.991240523384539 0.017301185451492

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---OverallCond

              grup_1            grup_2         istatistik          p_degeri
0  5.000000000000000 8.000000000000000  4.207797922797389 0.000029183965816
1  5.000000000000000 6.000000000000000  8.024601631084499 0.000000000000003
2  5.000000000000000 7.000000000000000  7.181787057425963 0.000000000001608
3  5.000000000000000 4.000000000000000  6.006797769384913 0.000000003099585
4  5.000000000000000 3.000000000000000  4.394394634450184 0.000012976826094
5  5.000000000000000 9.000000000000000 -0.189284125264436 0.849929407446802
6  5.000000000000000 2.000000000000000  0.542750822050922 0.587490921868024
7  8.000000000000000 6.000000000000000  0.566170743623825 0.571798061336160
8  8.000000000000000 7.000000000000000  0.552123539968134 0.581480159621676
9  8.000000000000000 4.000000000000000  3.536281194096965 0.000637746375124
10 8.000000000000000 3.000000000000000  3.503826125372361 0.000815936206961
11 8.000000000000000 9.000000000000000 -2.704298796815631 0.008640704133175
12 8.000000000000000 2.000000000000000 -0.583721432918711 0.561671022142542
13 6.000000000000000 7.000000000000000 -0.146884310606208 0.883312488940942
14 6.000000000000000 4.000000000000000  2.964902910964631 0.003355397317871
15 6.000000000000000 3.000000000000000  2.917567702927461 0.003931257793059
16 6.000000000000000 9.000000000000000 -3.144583121378719 0.001916624211046
17 6.000000000000000 2.000000000000000 -0.714560202593641 0.475757839891000
18 7.000000000000000 4.000000000000000  3.830339254032546 0.000176568507437
19 7.000000000000000 3.000000000000000  3.827336019640869 0.000187088190992
20 7.000000000000000 9.000000000000000 -3.752059989348508 0.000246878598551
21 7.000000000000000 2.000000000000000 -0.863651372479930 0.389196033405735
22 4.000000000000000 3.000000000000000  1.480926088371970 0.145161106502704
23 4.000000000000000 9.000000000000000 -4.624673918135374 0.000028569316221
24 4.000000000000000 2.000000000000000 -1.715150906850754 0.094462695949216
25 3.000000000000000 9.000000000000000 -3.678089197286346 0.001183342946555
26 3.000000000000000 2.000000000000000 -1.556379931236420 0.141929457013090
27 9.000000000000000 2.000000000000000  0.437062142226526 0.668732411268306

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---RoofStyle

    grup_1   grup_2         istatistik          p_degeri
0    Gable      Hip -8.958943642354843 0.000000000000000
1    Gable  Gambrel  0.926627783766151 0.354382535712280
2    Gable  Mansard -0.424976355243813 0.670961849285108
3    Gable     Flat -1.204118245233001 0.228880659635039
4      Hip  Gambrel  1.992578702578588 0.047449881816054
5      Hip  Mansard  0.880565672849426 0.379456435230499
6      Hip     Flat  0.328393719175290 0.742908925081434
7  Gambrel  Mansard -0.956273422648880 0.355156659243031
8  Gambrel     Flat -1.641381542389555 0.124676340230286
9  Mansard     Flat -0.710661664804647 0.495296479002776

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---RoofMatl

     grup_1   grup_2         istatistik          p_degeri
0   CompShg  WdShngl -6.084102558457283 0.000000001623246
1   CompShg  Membran                nan               nan
2   CompShg  WdShake -0.526265694599228 0.598811867461817
3   CompShg  Tar&Grv -0.307962103476117 0.758170496068191
4   CompShg     Roll                nan               nan
5   CompShg  ClyTile                nan               nan
6   WdShngl  Membran                nan               nan
7   WdShngl  WdShake  1.125997121996815 0.303178973324093
8   WdShngl  Tar&Grv  2.013572941839411 0.074894992974848
9   WdShngl     Roll                nan               nan
10  WdShngl  ClyTile                nan               nan
11  Membran  WdShake                nan               nan
12  Membran  Tar&Grv                nan               nan
13  Membran     Roll                nan               nan
14  Membran  ClyTile                nan               nan
15  WdShake  Tar&Grv  0.441012171541942 0.677620687258777
16  WdShake     Roll                nan               nan
17  WdShake  ClyTile                nan               nan
18  Tar&Grv     Roll                nan               nan
19  Tar&Grv  ClyTile                nan               nan
20     Roll  ClyTile                nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---MasVnrType

    grup_1  grup_2          istatistik          p_degeri
0  BrkFace    None  10.425094830818297 0.000000000000000
1  BrkFace   Stone  -6.076511616174615 0.000000002644996
2  BrkFace  BrkCmn   2.586907495911716 0.010106456345526
3     None   Stone -15.845093129163617 0.000000000000000
4     None  BrkCmn   1.208473966456016 0.227307171794017
5    Stone  BrkCmn   3.927423085953300 0.000140602200300

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---ExterQual

  grup_1 grup_2          istatistik          p_degeri
0     Gd     TA  25.312504793470264 0.000000000000000
1     Gd     Ex -11.438095683947449 0.000000000000000
2     Gd     Fa   5.088061359967873 0.000000557494581
3     TA     Ex -30.944809220831807 0.000000000000000
4     TA     Fa   3.393646407101728 0.000731522316372
5     Ex     Fa   6.561732362350887 0.000000026798627

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---ExterCond

  grup_1 grup_2         istatistik          p_degeri
0     TA     Fa  3.619021072089054 0.000310743367901
1     TA     Gd  2.666582845575190 0.007777709815741
2     TA     Ex -0.890550834120965 0.373390330165768
3     Fa     Gd -2.845555950515050 0.005235941477793
4     Fa     Ex -3.441918831363722 0.003631569588758
5     Gd     Ex -1.424441061542433 0.157312615610187

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Foundation

   grup_1  grup_2         istatistik          p_degeri
0   PConc  CBlock 17.954714958631527 0.000000000000000
1   PConc  BrkTil 11.014244313556793 0.000000000000000
2   PConc    Wood  1.238429272618252 0.216117867321311
3   PConc   Stone  1.800095183527337 0.072422841174625
4  CBlock  BrkTil  1.895599871922651 0.058522131755075
5  CBlock    Wood -0.173731774936351 0.862155088726271
6  CBlock   Stone -0.956601212001704 0.339282199686280
7  BrkTil    Wood -0.376222353713008 0.707405057168329
8  BrkTil   Stone -1.153064271143002 0.251066745759675
9    Wood   Stone -0.212026553919523 0.839105472319420

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---BsmtQual

  grup_1 grup_2          istatistik          p_degeri
0     Gd     TA  20.590014137077283 0.000000000000000
1     Gd     Ex -16.083943499324469 0.000000000000000
2     Gd     Fa   8.373780727496134 0.000000000000001
3     TA     Ex -29.693179684879517 0.000000000000000
4     TA     Fa   2.859596141665622 0.004413542026621
5     Ex     Fa  10.332785238452972 0.000000000000000

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---BsmtCond

  grup_1 grup_2         istatistik          p_degeri
0     TA     Gd -2.123774476014356 0.033921188350897
1     TA     Fa  4.619130713576428 0.000004335875385
2     TA     Po                nan               nan
3     Gd     Fa  7.162248545200044 0.000000000265924
4     Gd     Po                nan               nan
5     Fa     Po                nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---BsmtExposure

  grup_1 grup_2          istatistik          p_degeri
0     No     Gd -13.639412682672416 0.000000000000000
1     No     Mn  -3.166805822018540 0.001598182599751
2     No     Av  -8.565307376556651 0.000000000000000
3     Gd     Mn   5.361061956870686 0.000000245865834
4     Gd     Av   4.200624495894795 0.000036234787977
5     Mn     Av  -2.338059122724416 0.020139931978235

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---BsmtFinType1

   grup_1 grup_2         istatistik          p_degeri
0     GLQ    ALQ 10.285848606352499 0.000000000000000
1     GLQ    Unf 10.430100011219904 0.000000000000000
2     GLQ    Rec 10.510439390507145 0.000000000000000
3     GLQ    LwQ  7.255325667091271 0.000000000002300
4     GLQ    BLQ 10.152509069192412 0.000000000000000
5     ALQ    Unf -2.163292038710340 0.030989002227351
6     ALQ    Rec  2.932533737439429 0.003655955304246
7     ALQ    LwQ  1.458211942979964 0.146234609071770
8     ALQ    BLQ  2.392264855314982 0.017441873414365
9     Unf    Rec  4.189733664917222 0.000033679117555
10    Unf    LwQ  2.513361832299026 0.012353748023011
11    Unf    BLQ  3.793589148018849 0.000168960357266
12    Rec    LwQ -0.834784952089688 0.405091324068992
13    Rec    BLQ -0.470289715461783 0.638640782439055
14    LwQ    BLQ  0.415163710478979 0.678581742729748

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---BsmtFinType2

   grup_1 grup_2         istatistik          p_degeri
0     Unf    Rec  1.697913258330241 0.089833085893516
1     Unf    BLQ  2.888251541442227 0.003957852480023
2     Unf    GLQ -0.331200215929554 0.740563918535151
3     Unf    LwQ  2.184345559864453 0.029167359162024
4     Unf    ALQ -0.723963848188948 0.469260182493287
5     Rec    BLQ  1.688630392468418 0.096481617889371
6     Rec    GLQ -1.503844468029856 0.139311969647062
7     Rec    LwQ  0.566790009991418 0.572669851096169
8     Rec    ALQ -1.529484586627043 0.132708439226336
9     BLQ    GLQ -3.761296872063819 0.000619015052858
10    BLQ    LwQ -1.695485594148566 0.095345867796565
11    BLQ    ALQ -2.560123433792197 0.014805247351458
12    GLQ    LwQ  2.692471003433954 0.009925984081085
13    GLQ    ALQ -0.243010196638485 0.810151655400947
14    LwQ    ALQ -2.129057169984951 0.038634926742070

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Heating

  grup_1 grup_2        istatistik          p_degeri
0   GasA   GasW 0.587091632472628 0.557263859309121
1   GasA   Grav 1.684666630671563 0.092343172621117
2   GasA   OthW               nan               nan
3   GasW   Grav 1.511378229271881 0.150189877813766
4   GasW   OthW               nan               nan
5   Grav   OthW               nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---HeatingQC

  grup_1 grup_2         istatistik          p_degeri
0     Ex     Gd  8.809422067513605 0.000000000000000
1     Ex     TA 14.472440525799428 0.000000000000000
2     Ex     Fa  5.269383571965708 0.000000189259773
3     Ex     Po                nan               nan
4     Gd     TA  3.648571829244473 0.000293235790585
5     Gd     Fa  2.641489487876684 0.008910048018941
6     Gd     Po                nan               nan
7     TA     Fa  1.245283493680474 0.213930197670188
8     TA     Po                nan               nan
9     Fa     Po                nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---CentralAir

  grup_1 grup_2        istatistik          p_degeri
0      Y      N 7.184377846440295 0.000000000001248

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Electrical

  grup_1 grup_2         istatistik          p_degeri
0  SBrkr  FuseF  3.578306492325499 0.000362053436145
1  SBrkr  FuseA  6.575394256865532 0.000000000075596
2  SBrkr  FuseP  1.476643555717856 0.140083229179169
3  SBrkr    Mix                nan               nan
4  FuseF  FuseA -1.021721900322170 0.309992334943901
5  FuseF  FuseP  0.451537948500297 0.658061830670910
6  FuseF    Mix                nan               nan
7  FuseA  FuseP  0.793814791295105 0.430105796250349
8  FuseA    Mix                nan               nan
9  FuseP    Mix                nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---BsmtFullBath

             grup_1            grup_2         istatistik          p_degeri
0 1.000000000000000 0.000000000000000  7.571083153505922 0.000000000000079
1 1.000000000000000 2.000000000000000 -0.348620715469275 0.727537119432917
2 0.000000000000000 2.000000000000000 -2.221136433095686 0.026685005510342

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---BsmtHalfBath

             grup_1            grup_2        istatistik          p_degeri
0 0.000000000000000 1.000000000000000 1.433863609530216 0.151897720427450
1 0.000000000000000 2.000000000000000               nan               nan
2 1.000000000000000 2.000000000000000               nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---FullBath

             grup_1            grup_2          istatistik          p_degeri
0 2.000000000000000 1.000000000000000  21.959205105633668 0.000000000000000
1 2.000000000000000 3.000000000000000  -9.194267497689196 0.000000000000000
2 2.000000000000000 0.000000000000000   1.631518465128765 0.103314582272067
3 1.000000000000000 3.000000000000000 -20.610711985385510 0.000000000000000
4 1.000000000000000 0.000000000000000  -1.908992415030047 0.056859101063725
5 3.000000000000000 0.000000000000000   2.641834468556536 0.012971851550490

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---HalfBath

             grup_1            grup_2        istatistik          p_degeri
0 1.000000000000000 0.000000000000000 9.433392760539277 0.000000000000000
1 1.000000000000000 2.000000000000000 1.531873632927012 0.126311886299626
2 0.000000000000000 2.000000000000000 0.287333427154728 0.773944568077590

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---BedroomAbvGr

              grup_1            grup_2         istatistik          p_degeri
0  3.000000000000000 4.000000000000000 -6.695592680824925 0.000000000041439
1  3.000000000000000 1.000000000000000 -1.603463827127646 0.109323349893252
2  3.000000000000000 2.000000000000000  4.342706736208906 0.000015693405844
3  3.000000000000000 0.000000000000000 -1.364748917083717 0.172827854450817
4  3.000000000000000 5.000000000000000  0.055305850242548 0.955912363564440
5  3.000000000000000 6.000000000000000  0.762954711166104 0.445781531329121
6  4.000000000000000 1.000000000000000  1.084826604813300 0.279449280097612
7  4.000000000000000 2.000000000000000  7.354254767761507 0.000000000000993
8  4.000000000000000 0.000000000000000  0.037668973376603 0.969999775112292
9  4.000000000000000 5.000000000000000  1.518934673883253 0.130681228215763
10 4.000000000000000 6.000000000000000  1.122786662180624 0.263264258784886
11 1.000000000000000 2.000000000000000  2.662601457701310 0.008172262467412
12 1.000000000000000 0.000000000000000 -0.376436192826743 0.709241951774815
13 1.000000000000000 5.000000000000000  0.652039479871806 0.518105167632995
14 1.000000000000000 6.000000000000000  0.721988193275301 0.476083529248762
15 2.000000000000000 0.000000000000000 -1.711968661820428 0.088025723293378
16 2.000000000000000 5.000000000000000 -0.994286025956368 0.320924107452240
17 2.000000000000000 6.000000000000000  0.158677174243479 0.874039686709044
18 0.000000000000000 5.000000000000000  1.003388226569738 0.330607904708590
19 0.000000000000000 6.000000000000000  0.961900375181555 0.380277066389639
20 5.000000000000000 6.000000000000000  0.691702320864419 0.499691463498555

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---KitchenAbvGr

             grup_1            grup_2        istatistik          p_degeri
0 1.000000000000000 2.000000000000000 3.718676556938005 0.000210454747781
1 1.000000000000000 3.000000000000000               nan               nan
2 2.000000000000000 3.000000000000000               nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---KitchenQual

  grup_1 grup_2          istatistik          p_degeri
0     Gd     TA  21.971910060609833 0.000000000000000
1     Gd     Ex -13.570111591673548 0.000000000000000
2     Gd     Fa   6.827221042438956 0.000000000026656
3     TA     Ex -29.928498584073186 0.000000000000000
4     TA     Fa   2.982788310729176 0.002983726496929
5     Ex     Fa   8.340975672888023 0.000000000000236

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Functional

   grup_1 grup_2         istatistik          p_degeri
0     Typ   Min1  2.529296891411822 0.011575547020514
1     Typ   Maj1  0.982653544059015 0.326008293060742
2     Typ   Min2  2.741268988445011 0.006224463978758
3     Typ    Mod -0.647682135488358 0.517334615999767
4     Typ   Maj2  2.271514163519238 0.023322286839290
5    Min1   Maj1 -1.265019471354001 0.215935420097954
6    Min1   Min2 -0.019129157862582 0.984824554305037
7    Min1    Mod -2.163713712013665 0.038863399958596
8    Min1   Maj2  3.019226752058092 0.006108043237413
9    Maj1   Min2  1.096008435744114 0.281009441790276
10   Maj1    Mod -0.964124184149830 0.347758734075270
11   Maj1   Maj2  2.229288689157647 0.045669180427616
12   Min2    Mod -2.186975654292507 0.035936926413498
13   Min2   Maj2  2.149984599203794 0.040673235642445
14    Mod   Maj2  1.685657339976558 0.117666099760692

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Fireplaces

             grup_1            grup_2          istatistik          p_degeri
0 0.000000000000000 1.000000000000000 -17.127749726104362 0.000000000000000
1 0.000000000000000 2.000000000000000 -13.469232105882893 0.000000000000000
2 0.000000000000000 3.000000000000000  -5.385849297935135 0.000000109995942
3 1.000000000000000 2.000000000000000  -2.893876626447513 0.003948958779490
4 1.000000000000000 3.000000000000000  -1.174433920395221 0.240775871451274
5 2.000000000000000 3.000000000000000  -0.248817471789599 0.804147700464489

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---GarageType

     grup_1   grup_2          istatistik          p_degeri
0    Attchd   Detchd  14.940227135208872 0.000000000000000
1    Attchd  BuiltIn  -5.742227530269596 0.000000013633139
2    Attchd  CarPort   2.848529477346061 0.004524117037646
3    Attchd  Basment   2.135234316208730 0.033091910262993
4    Attchd   2Types   1.597255322173188 0.110671329544372
5    Detchd  BuiltIn -16.469498397271686 0.000000000000000
6    Detchd  CarPort   1.316400813064999 0.188955890434345
7    Detchd  Basment  -2.277931691756126 0.023354496799554
8    Detchd   2Types  -0.705309829755528 0.481118016633841
9   BuiltIn  CarPort   3.403917882344487 0.001125550717085
10  BuiltIn  Basment   3.568807247680955 0.000625345396999
11  BuiltIn   2Types   2.388526774975090 0.019784326828296
12  CarPort  Basment  -1.667755636015276 0.111761995688307
13  CarPort   2Types  -1.827133517653776 0.100954009155322
14  Basment   2Types   0.393159932587911 0.698818960493115

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---GarageFinish

  grup_1 grup_2          istatistik          p_degeri
0    RFn    Unf  16.681471906161743 0.000000000000000
1    RFn    Fin  -6.585099395136154 0.000000000098533
2    Unf    Fin -20.052543795293449 0.000000000000000

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---GarageCars

             grup_1            grup_2          istatistik          p_degeri
0 2.000000000000000 3.000000000000000 -21.405364406843741 0.000000000000000
1 2.000000000000000 1.000000000000000  17.441861704136254 0.000000000000000
2 2.000000000000000 4.000000000000000  -0.594591526032154 0.552334162260410
3 3.000000000000000 1.000000000000000  27.606318983788398 0.000000000000000
4 3.000000000000000 4.000000000000000   2.044236723780317 0.042481831382623
5 1.000000000000000 4.000000000000000  -4.553835628894801 0.000007588148464

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---GarageQual

  grup_1 grup_2         istatistik          p_degeri
0     TA     Fa  5.354307178252786 0.000000104982211
1     TA     Gd -0.341385347182481 0.732882465431939
2     TA     Ex -1.060256696564417 0.289275908040713
3     TA     Po  1.868121984357670 0.062028279014714
4     Fa     Gd -4.379016006689067 0.000053904274272
5     Fa     Ex -3.280895155029071 0.001954601524422
6     Fa     Po  0.911133310032037 0.366874693232324
7     Gd     Ex -0.611535876673900 0.552254460303693
8     Gd     Po  2.179767814802431 0.049914572433196
9     Ex     Po  1.185829730286913 0.301317133189953

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---GarageCond

  grup_1 grup_2         istatistik          p_degeri
0     TA     Fa  5.154188153334081 0.000000302801200
1     TA     Gd  1.069753559704933 0.284975400492419
2     TA     Po  2.454019647881794 0.014287835907474
3     TA     Ex  1.118941494528423 0.263421009435702
4     Fa     Gd -2.500411439354443 0.017389449879689
5     Fa     Po  0.454154295183258 0.652521740475368
6     Fa     Ex -0.501092671590542 0.619845636988700
7     Gd     Po  2.850196066774112 0.019083082228863
8     Gd     Ex  1.297525412808785 0.251086095364805
9     Po     Ex -0.975563270961487 0.366956967189336

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---PavedDrive

  grup_1 grup_2         istatistik          p_degeri
0      Y      N  5.386732197765001 0.000000088218354
1      Y      P  3.427159352062848 0.000633709105710
2      N      P -0.524812717358825 0.601395576544147

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---PoolArea

                grup_1              grup_2  istatistik  p_degeri
0    0.000000000000000 512.000000000000000         nan       nan
1    0.000000000000000 648.000000000000000         nan       nan
2    0.000000000000000 576.000000000000000         nan       nan
3    0.000000000000000 555.000000000000000         nan       nan
4    0.000000000000000 480.000000000000000         nan       nan
5    0.000000000000000 519.000000000000000         nan       nan
6  512.000000000000000 648.000000000000000         nan       nan
7  512.000000000000000 576.000000000000000         nan       nan
8  512.000000000000000 555.000000000000000         nan       nan
9  512.000000000000000 480.000000000000000         nan       nan
10 512.000000000000000 519.000000000000000         nan       nan
11 648.000000000000000 576.000000000000000         nan       nan
12 648.000000000000000 555.000000000000000         nan       nan
13 648.000000000000000 480.000000000000000         nan       nan
14 648.000000000000000 519.000000000000000         nan       nan
15 576.000000000000000 555.000000000000000         nan       nan
16 576.000000000000000 480.000000000000000         nan       nan
17 576.000000000000000 519.000000000000000         nan       nan
18 555.000000000000000 480.000000000000000         nan       nan
19 555.000000000000000 519.000000000000000         nan       nan
20 480.000000000000000 519.000000000000000         nan       nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---YrSold

,grup_1,grup_2,istatistik,p_degeri
0,2008.000000000000000,2007.000000000000000,-0.947204633026629,0.344022286792131
1,2008.000000000000000,2006.000000000000000,-0.262563402346487,0.793001914644192
2,2008.000000000000000,2009.000000000000000,-0.396898680727160,0.691621953330166
3,2008.000000000000000,2010.000000000000000,-0.205848705027895,0.837027758021460
4,2007.000000000000000,2006.000000000000000,0.678530964213788,0.497755419992036
5,2007.000000000000000,2009.000000000000000,0.526780792431243,0.598584205881586
6,2007.000000000000000,2010.000000000000000,0.551158166635590,0.581856128090548
7,2006.000000000000000,2009.000000000000000,-0.139171608365582,0.889371491443085
8,2006.000000000000000,2010.000000000000000,0.010829009512343,0.991365643372146
9,2009.000000000000000,2010.000000000000000,0.121907652908372,0.903037629153761

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---SaleType

   grup_1 grup_2          istatistik          p_degeri
0      WD    New -13.172804977847768 0.000000000000000
1      WD    COD   3.296736201932874 0.001014136286100
2      WD  ConLI  -1.202048118835841 0.229651197906959
3      WD    CWD  -0.897469552929717 0.369700683193716
4      WD  ConLw   0.347677324041589 0.728161200125543
5      WD    Con  -1.766969074433129 0.077562059396426
6      WD  ConLD   0.885446682810969 0.376144396362342
7      WD    Oth                 nan               nan
8     New    COD   7.706768707141944 0.000000000001871
9     New  ConLI   0.800531264324063 0.425025606745326
10    New    CWD   1.300296114640352 0.196033469866587
11    New  ConLw   2.202938746719437 0.029541795117998
12    New    Con   0.111865768723279 0.911123180564824
13    New  ConLD   2.816279268382211 0.005688956616453
14    New    Oth                 nan               nan
15    COD  ConLI  -2.555690667305366 0.015550225943171
16    COD    CWD  -3.154923867232096 0.003415066123342
17    COD  ConLw  -1.410089081675556 0.167869693775220
18    COD    Con  -4.501956688227867 0.000089025196451
19    COD  ConLD  -0.721980768838608 0.475242804624169
20    COD    Oth                 nan               nan
21  ConLI    CWD   0.172728594517196 0.869639080449244
22  ConLI  ConLw   0.649964969310306 0.544390715226932
23  ConLI    Con  -0.271444773551218 0.803656208654586
24  ConLI  ConLD   0.915702774676219 0.395134824087361
25  ConLI    Oth                 nan               nan
26    CWD  ConLw   0.893635555582573 0.405931966495127
27    CWD    Con  -0.809596104051140 0.463581627092739
28    CWD  ConLD   1.310797608716451 0.231289960346931
29    CWD    Oth                 nan               nan
30  ConLw    Con  -1.961566612651531 0.121336499462770
31  ConLw  ConLD   0.434371399333218 0.677093543579055
32  ConLw    Oth                 nan               nan
33    Con  ConLD   2.369886197190402 0.063961707027885
34    Con    Oth                 nan               nan
35  ConLD    Oth                 nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---SaleCondition

     grup_1   grup_2          istatistik          p_degeri
0    Normal  Abnorml   3.231633208202880 0.001273272339618
1    Normal  Partial -12.853165447301809 0.000000000000000
2    Normal   Family   1.845629038751342 0.065275845013828
3    Normal   Alloca   0.573742877347995 0.566287746115910
4    Normal  AdjLand                 nan               nan
5   Abnorml  Partial  -8.457701768716284 0.000000000000008
6   Abnorml   Family   0.088410211549541 0.929756198517993
7   Abnorml   Alloca  -0.319597461223194 0.750174038989891
8   Abnorml  AdjLand                 nan               nan
9   Partial   Family   5.173829464034377 0.000000811039988
10  Partial   Alloca   2.620420605015997 0.009888903911195
11  Partial  AdjLand                 nan               nan
12   Family   Alloca  -0.464310413338954 0.646987329319034
13   Family  AdjLand                 nan               nan
14   Alloca  AdjLand                 nan               nan

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Neighborhood

      grup_1   grup_2          istatistik          p_degeri
0    CollgCr  Veenker  -3.004350308930777 0.003207102735701
1    CollgCr  Crawfor  -0.442207081208295 0.658932813057049
2    CollgCr  NoRidge  -9.517411999799641 0.000000000000000
3    CollgCr  Mitchel   4.157179174151181 0.000053977139586
4    CollgCr  Somerst  -4.083747886250396 0.000064647845292
5    CollgCr  OldTown   9.331361446763662 0.000000000000000
6    CollgCr  BrkSide   7.688298379455023 0.000000000001360
7    CollgCr   Sawyer   7.919741601783382 0.000000000000341
8    CollgCr  NridgHt -11.348790560771381 0.000000000000000
9    CollgCr  SawyerW   0.927444956938561 0.355058460592353
10   CollgCr    NAmes  10.436688546421539 0.000000000000000
11   CollgCr   IDOTRR   9.631664824219198 0.000000000000000
12   CollgCr  MeadowV   5.888886268853716 0.000000031310064
13   CollgCr   Timber  -4.859589059487320 0.000002950507176
14   CollgCr  StoneBr  -9.141106531314385 0.000000000000001
15   CollgCr  ClearCr  -0.900840311537052 0.369326374529277
16   CollgCr  Gilbert   0.597353938719008 0.551070615176063
17   CollgCr  Edwards   8.638062406690487 0.000000000000003
18   CollgCr   NWAmes   1.811101762074352 0.071943969903053
19   CollgCr  NPkVill   2.867820815085765 0.004840965800787
20   CollgCr  Blmngtn   0.519937479038893 0.603965035197716
21   CollgCr   BrDale   7.212881699256418 0.000000000035492
22   CollgCr    SWISU   4.809040977553653 0.000003892628536
23   CollgCr  Blueste   1.734527772277948 0.085350167386780
24   Veenker  Crawfor   1.929638582893053 0.059832528623769
25   Veenker  NoRidge  -1.537379795592924 0.132486268058472
26   Veenker  Mitchel   5.456445523784482 0.000004022712673
27   Veenker  Somerst   1.204929509008975 0.231782861305081
28   Veenker  OldTown   5.737488623054332 0.000000100932683
29   Veenker  BrkSide   7.138293087384262 0.000000005044460
..       ...      ...                 ...               ...
270  ClearCr    SWISU   4.236002171693273 0.000222508018487
271  ClearCr  Blueste   1.733363343899981 0.110932317489934
272  Gilbert  Edwards   7.276001580694862 0.000000000050273
273  Gilbert   NWAmes   1.224301010585111 0.223964593363406
274  Gilbert  NPkVill   3.089599746218608 0.003164866412073
275  Gilbert  Blmngtn   0.188141129469705 0.851390506798746
276  Gilbert   BrDale   8.021882747291023 0.000000000036261
277  Gilbert    SWISU   4.852683996225166 0.000007783939587
278  Gilbert  Blueste   1.887798690803670 0.064982219592908
279  Edwards   NWAmes  -6.255387421877946 0.000000008138777
280  Edwards  NPkVill  -0.532144042667471 0.596311258195925
281  Edwards  Blmngtn  -4.654922173478776 0.000013266649686
282  Edwards   BrDale   2.759936362168298 0.007202335713786
283  Edwards    SWISU  -0.556535531188508 0.579360503813726
284  Edwards  Blueste  -0.047776409094572 0.962040932452468
285   NWAmes  NPkVill   2.911419265472396 0.005362051557684
286   NWAmes  Blmngtn  -0.717394941117140 0.476060221536810
287   NWAmes   BrDale   8.335775307989003 0.000000000016802
288   NWAmes    SWISU   4.425534401844936 0.000039685097724
289   NWAmes  Blueste   1.834798925168368 0.073151152589780
290  NPkVill  Blmngtn  -3.907214908024420 0.000947073674425
291  NPkVill   BrDale   6.621052155237760 0.000001898799335
292  NPkVill    SWISU   0.208877523914223 0.836306554184008
293  NPkVill  Blueste   0.820929844990292 0.438745334411423
294  Blmngtn   BrDale   9.754218362825140 0.000000000241504
295  Blmngtn    SWISU   4.369097895081621 0.000129718575730
296  Blmngtn  Blueste   2.373799231187401 0.032455480212137
297   BrDale    SWISU  -3.952414294134087 0.000400261224413
298   BrDale  Blueste  -2.894042901170330 0.011128286092205
299    SWISU  Blueste   0.182138981166156 0.857402883150342

[300 rows x 4 columns]

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Exterior1st

     grup_1   grup_2         istatistik          p_degeri
0   VinylSd  MetalSd 10.438954928160880 0.000000000000000
1   VinylSd  Wd Sdng  8.998157144549847 0.000000000000000
2   VinylSd  BrkFace  1.507970490816364 0.132256085798770
3   VinylSd  HdBoard  7.755533242584619 0.000000000000041
4   VinylSd  WdShing  3.119589073760575 0.001930366331355
5   VinylSd  CemntBd -3.165902581740842 0.001647802776081
6   VinylSd   Stucco  2.736753854193900 0.006457882651082
7   VinylSd  Plywood  4.474117469340855 0.000009577924414
8   VinylSd  AsbShng  4.844606472487682 0.000001769856921
9   VinylSd  BrkComm                nan               nan
10  VinylSd    Stone                nan               nan
11  VinylSd  ImStucc                nan               nan
12  VinylSd   CBlock                nan               nan
13  MetalSd  Wd Sdng -0.310089137096592 0.756695653694896
14  MetalSd  BrkFace -4.392145294388903 0.000017943218173
15  MetalSd  HdBoard -1.651297560149716 0.099655743565944
16  MetalSd  WdShing -0.920302018044602 0.358581926194680
17  MetalSd  CemntBd -9.038339024739805 0.000000000000000
18  MetalSd   Stucco -1.200404554045485 0.231492644565145
19  MetalSd  Plywood -2.956837984669341 0.003426391782742
20  MetalSd  AsbShng  2.241293871134317 0.026202135117965
21  MetalSd  BrkComm                nan               nan
22  MetalSd    Stone                nan               nan
23  MetalSd  ImStucc                nan               nan
24  MetalSd   CBlock                nan               nan
25  Wd Sdng  BrkFace -3.307934680566078 0.001131544838134
26  Wd Sdng  HdBoard -1.130291129332454 0.259262472940234
27  Wd Sdng  WdShing -0.584329215942190 0.559787356871702
28  Wd Sdng  CemntBd -7.366729339814891 0.000000000005037
29  Wd Sdng   Stucco -0.801077732256466 0.424238683550975
..      ...      ...                ...               ...
61  WdShing  ImStucc                nan               nan
62  WdShing   CBlock                nan               nan
63  CemntBd   Stucco  3.103991618636517 0.002893498796945
64  CemntBd  Plywood  5.251229824663827 0.000000773609842
65  CemntBd  AsbShng  4.474583602686438 0.000037122552878
66  CemntBd  BrkComm                nan               nan
67  CemntBd    Stone                nan               nan
68  CemntBd  ImStucc                nan               nan
69  CemntBd   CBlock                nan               nan
70   Stucco  Plywood -0.427489372784617 0.670171407459456
71   Stucco  AsbShng  2.415833090529373 0.021996481245951
72   Stucco  BrkComm                nan               nan
73   Stucco    Stone                nan               nan
74   Stucco  ImStucc                nan               nan
75   Stucco   CBlock                nan               nan
76  Plywood  AsbShng  4.083974768184766 0.000108559287807
77  Plywood  BrkComm                nan               nan
78  Plywood    Stone                nan               nan
79  Plywood  ImStucc                nan               nan
80  Plywood   CBlock                nan               nan
81  AsbShng  BrkComm                nan               nan
82  AsbShng    Stone                nan               nan
83  AsbShng  ImStucc                nan               nan
84  AsbShng   CBlock                nan               nan
85  BrkComm    Stone                nan               nan
86  BrkComm  ImStucc                nan               nan
87  BrkComm   CBlock                nan               nan
88    Stone  ImStucc                nan               nan
89    Stone   CBlock                nan               nan
90  ImStucc   CBlock                nan               nan

[91 rows x 4 columns]

SalePrice iÃ§in karÅŸÄ±laÅŸtÄ±rma---Exterior2nd

      grup_1   grup_2         istatistik          p_degeri
0    VinylSd  MetalSd 10.414645622725612 0.000000000000000
1    VinylSd  Wd Shng  3.168252939456682 0.001640946670886
2    VinylSd  HdBoard  7.104304932725857 0.000000000003777
3    VinylSd  Wd Sdng  9.321565776886054 0.000000000000000
4    VinylSd  Plywood  5.796502287883316 0.000000012110756
5    VinylSd  CmentBd -2.871116720827944 0.004281093336051
6    VinylSd  BrkFace  1.081861695656623 0.279921730031305
7    VinylSd   Stucco  3.842000252905507 0.000140424355969
8    VinylSd  AsbShng  4.714199972873501 0.000003294757930
9    VinylSd  Brk Cmn  2.639835181032030 0.008606498328321
10   VinylSd  ImStucc -1.305115143779298 0.192569900044136
11   VinylSd  AsphShn  1.125129604064487 0.261189144160151
12   VinylSd    Other                nan               nan
13   VinylSd    Stone  0.309140940178698 0.757370590704058
14   VinylSd   CBlock                nan               nan
15   MetalSd  Wd Shng -1.540580213781315 0.125040155648154
16   MetalSd  HdBoard -1.911463314197648 0.056882092774287
17   MetalSd  Wd Sdng -0.348104613915718 0.727996368464678
18   MetalSd  Plywood -2.478452609619743 0.013858862140419
19   MetalSd  CmentBd -8.933472872411439 0.000000000000000
20   MetalSd  BrkFace -3.450226069323119 0.000693038846147
21   MetalSd   Stucco -0.048079643372982 0.961704080349943
22   MetalSd  AsbShng  1.853943586473548 0.065365525306624
23   MetalSd  Brk Cmn  0.695028410399478 0.487969947032083
24   MetalSd  ImStucc -4.484008068641080 0.000013175512939
25   MetalSd  AsphShn -0.164750565179443 0.869337207107910
26   MetalSd    Other                nan               nan
27   MetalSd    Stone -1.320956039182693 0.188301845096607
28   MetalSd   CBlock                nan               nan
29   Wd Shng  HdBoard  0.314188539255620 0.753777161932118
..       ...      ...                ...               ...
90   BrkFace    Stone -0.045732949958858 0.964000358259145
91   BrkFace   CBlock                nan               nan
92    Stucco  AsbShng  1.574660890286360 0.124874431656301
93    Stucco  Brk Cmn  0.652284178564181 0.520416886942155
94    Stucco  ImStucc -2.196517146861351 0.036821593746659
95    Stucco  AsphShn -0.138128829223816 0.891519859687095
96    Stucco    Other                nan               nan
97    Stucco    Stone -1.206718742260056 0.241620401416787
98    Stucco   CBlock                nan               nan
99   AsbShng  Brk Cmn -0.588110971381108 0.563383753883661
100  AsbShng  ImStucc -2.525742742163879 0.019251670114744
101  AsbShng  AsphShn -1.106783598010090 0.285821728947495
102  AsbShng    Other                nan               nan
103  AsbShng    Stone -2.564420110002801 0.021571987220901
104  AsbShng   CBlock                nan               nan
105  Brk Cmn  ImStucc -1.458490725789956 0.168439951226336
106  Brk Cmn  AsphShn -0.801823395869667 0.453232196082916
107  Brk Cmn    Other                nan               nan
108  Brk Cmn    Stone -2.317581714372409 0.059646167433826
109  Brk Cmn   CBlock                nan               nan
110  ImStucc  AsphShn  0.673662000612990 0.517451290687934
111  ImStucc    Other                nan               nan
112  ImStucc    Stone  0.364015963003772 0.724251048101684
113  ImStucc   CBlock                nan               nan
114  AsphShn    Other                nan               nan
115  AsphShn    Stone -1.451531175256171 0.283746028240531
116  AsphShn   CBlock                nan               nan
117    Other    Stone                nan               nan
118    Other   CBlock                nan               nan
119    Stone   CBlock                nan               nan

[120 rows x 4 columns]

kategorik iliÅŸkili oldugunu dusundugum Ã¶zellikler
* MSZoning
* LotShape belki
* LandContour
* BldgType
* HouseStyle
* OverallQual
* MasVnrType
* ExterQual
* ExterCond
* BsmtQual
* BsmtCond
* BsmtExposure
* BsmtFinType1
* HeatingQC
* CentralAir
* BsmtFullBath
* FullBath
* KitchenAbvGr belki
* KitchenQual
* Functional belki
* Fireplaces
* GarageType
* GarageFinish
* GarageCars
* PavedDrive
* poolArea velki
* SaleCondition velki
* Neighborhood
* Exterior1st velki

In [40]:
def kategorik_num(a,emlak):
    deneme=dict()
    for i in range(emlak[a].nunique()):
        deneme[emlak[a].unique()[i]]=i
    emlak[a+"_n"] = emlak[a].replace(deneme)
    return emlak[a+"_n"]

for a in listekategorik.columns:
    emlak[a+"_n"]=kategorik_num(a,emlak)
    listekategorik[a+"_n"]=kategorik_num(a,emlak)

In [41]:
listekategorik.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1094 entries, 0 to 1459
Data columns (total 98 columns):
MSZoning           1094 non-null object
Street             1094 non-null object
LotShape           1094 non-null object
LandContour        1094 non-null object
LotConfig          1094 non-null object
LandSlope          1094 non-null object
Condition1         1094 non-null object
Condition2         1094 non-null object
BldgType           1094 non-null object
HouseStyle         1094 non-null object
OverallQual        1094 non-null int64
OverallCond        1094 non-null int64
RoofStyle          1094 non-null object
RoofMatl           1094 non-null object
MasVnrType         1094 non-null object
ExterQual          1094 non-null object
ExterCond          1094 non-null object
Foundation         1094 non-null object
BsmtQual           1094 non-null object
BsmtCond           1094 non-null object
BsmtExposure       1094 non-null object
BsmtFinType1       1094 non-null object
BsmtFinType2       1094 non-null object
Heating            1094 non-null object
HeatingQC          1094 non-null object
CentralAir         1094 non-null object
Electrical         1094 non-null object
BsmtFullBath       1094 non-null int64
BsmtHalfBath       1094 non-null int64
FullBath           1094 non-null int64
HalfBath           1094 non-null int64
BedroomAbvGr       1094 non-null int64
KitchenAbvGr       1094 non-null int64
KitchenQual        1094 non-null object
Functional         1094 non-null object
Fireplaces         1094 non-null int64
GarageType         1094 non-null object
GarageFinish       1094 non-null object
GarageCars         1094 non-null int64
GarageQual         1094 non-null object
GarageCond         1094 non-null object
PavedDrive         1094 non-null object
PoolArea           1094 non-null int64
YrSold             1094 non-null int64
SaleType           1094 non-null object
SaleCondition      1094 non-null object
Neighborhood       1094 non-null object
Exterior1st        1094 non-null object
Exterior2nd        1094 non-null object
MSZoning_n         1094 non-null int64
Street_n           1094 non-null int64
LotShape_n         1094 non-null int64
LandContour_n      1094 non-null int64
LotConfig_n        1094 non-null int64
LandSlope_n        1094 non-null int64
Condition1_n       1094 non-null int64
Condition2_n       1094 non-null int64
BldgType_n         1094 non-null int64
HouseStyle_n       1094 non-null int64
OverallQual_n      1094 non-null int64
OverallCond_n      1094 non-null int64
RoofStyle_n        1094 non-null int64
RoofMatl_n         1094 non-null int64
MasVnrType_n       1094 non-null int64
ExterQual_n        1094 non-null int64
ExterCond_n        1094 non-null int64
Foundation_n       1094 non-null int64
BsmtQual_n         1094 non-null int64
BsmtCond_n         1094 non-null int64
BsmtExposure_n     1094 non-null int64
BsmtFinType1_n     1094 non-null int64
BsmtFinType2_n     1094 non-null int64
Heating_n          1094 non-null int64
HeatingQC_n        1094 non-null int64
CentralAir_n       1094 non-null int64
Electrical_n       1094 non-null int64
BsmtFullBath_n     1094 non-null int64
BsmtHalfBath_n     1094 non-null int64
FullBath_n         1094 non-null int64
HalfBath_n         1094 non-null int64
BedroomAbvGr_n     1094 non-null int64
KitchenAbvGr_n     1094 non-null int64
KitchenQual_n      1094 non-null int64
Functional_n       1094 non-null int64
Fireplaces_n       1094 non-null int64
GarageType_n       1094 non-null int64
GarageFinish_n     1094 non-null int64
GarageCars_n       1094 non-null int64
GarageQual_n       1094 non-null int64
GarageCond_n       1094 non-null int64
PavedDrive_n       1094 non-null int64
PoolArea_n         1094 non-null int64
YrSold_n           1094 non-null int64
SaleType_n         1094 non-null int64
SaleCondition_n    1094 non-null int64
Neighborhood_n     1094 non-null int64
Exterior1st_n      1094 non-null int64
Exterior2nd_n      1094 non-null int64
dtypes: int64(61), object(37)
memory usage: 846.1+ KB

In [42]:
Y = emlak['SalePrice']
X = emlak[['MSZoning_n','LotShape_n','LandContour_n','BldgType_n','HouseStyle_n','OverallQual_n','MasVnrType_n','ExterQual_n','ExterCond_n','BsmtQual_n','BsmtCond_n',
          'BsmtExposure_n','BsmtFinType1_n','HeatingQC_n','CentralAir_n','BsmtFullBath_n','FullBath_n','KitchenAbvGr_n','KitchenQual_n',
          'Functional_n','Fireplaces_n','GarageType_n','GarageFinish_n','GarageCars_n','PavedDrive_n','PoolArea_n','SaleCondition_n','Neighborhood_n','Exterior1st_n',
          'YearBuilt','YearRemodAdd','GarageYrBlt','TotalBsmtSF','1stFlrSF','1stFlrSF','GrLivArea','TotRmsAbvGrd','GarageArea','MiscVal']]

In [43]:
lrm = linear_model.LinearRegression()
lrm.fit(X, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [44]:
print('DeÄŸiÅŸkenler: \n', lrm.coef_)
print('Sabit deÄŸer (bias): \n', lrm.intercept_)

DeÄŸiÅŸkenler:
 [ 1.26265757e+03  4.30802559e+03  4.54482958e+03 -1.42131031e+03
 -1.95190739e+02  2.54262934e+03 -5.45527667e+02 -5.55478039e+02
  6.30006985e+02  9.06443411e+03 -3.84024648e+03  2.06508029e+03
 -3.07732311e+03 -3.61386756e+03 -2.66731583e+02 -1.07218030e+04
  9.17959338e+03 -3.97130295e+04  7.73788149e+03 -6.68375053e+03
  1.53043290e+04 -3.89044045e+03  2.76156451e+03  6.09021120e+03
 -1.98201746e+03 -2.96430786e+04  1.15886829e+03 -9.68526680e+02
 -8.85290244e+01  6.15997965e+02  5.44115736e+02 -4.17465164e+01
  1.86354329e+01  2.97262097e+00  2.97262096e+00  6.81930480e+01
  3.09852584e+03  5.23031249e+01  8.36296530e+00]
Sabit deÄŸer (bias):
 -2216546.1115838797

In [45]:
import statsmodels.api as sm

X = sm.add_constant(X)
results = sm.OLS(Y, X).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.802
Model:                            OLS   Adj. R-squared:                  0.795
Method:                 Least Squares   F-statistic:                     112.3
Date:                Wed, 22 May 2019   Prob (F-statistic):               0.00
Time:                        02:40:47   Log-Likelihood:                -13060.
No. Observations:                1094   AIC:                         2.620e+04
Df Residuals:                    1055   BIC:                         2.639e+04
Df Model:                          38
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const           -2.217e+06   1.95e+05    -11.367      0.000    -2.6e+06   -1.83e+06
MSZoning_n       1262.6576   1647.238      0.767      0.444   -1969.577    4494.893
LotShape_n       4308.0256   2327.951      1.851      0.065    -259.916    8875.967
LandContour_n    4544.8296   1873.055      2.426      0.015     869.493    8220.166
BldgType_n      -1421.3103   1477.459     -0.962      0.336   -4320.403    1477.782
HouseStyle_n     -195.1907   1004.702     -0.194      0.846   -2166.632    1776.251
OverallQual_n    2542.6293    918.135      2.769      0.006     741.051    4344.208
MasVnrType_n     -545.5277   1877.393     -0.291      0.771   -4229.376    3138.321
ExterQual_n      -555.4780   2646.634     -0.210      0.834   -5748.744    4637.788
ExterCond_n       630.0070   2000.702      0.315      0.753   -3295.801    4555.815
BsmtQual_n       9064.4341   1885.588      4.807      0.000    5364.506    1.28e+04
BsmtCond_n      -3840.2465   2903.893     -1.322      0.186   -9538.309    1857.816
BsmtExposure_n   2065.0803   1122.385      1.840      0.066    -137.281    4267.441
BsmtFinType1_n  -3077.3231    891.455     -3.452      0.001   -4826.550   -1328.096
HeatingQC_n     -3613.8676   1653.761     -2.185      0.029   -6858.903    -368.832
CentralAir_n     -266.7316   5924.878     -0.045      0.964   -1.19e+04    1.14e+04
BsmtFullBath_n  -1.072e+04   2429.667     -4.413      0.000   -1.55e+04   -5954.274
FullBath_n       9179.5934   2573.763      3.567      0.000    4129.316    1.42e+04
KitchenAbvGr_n  -3.971e+04   7770.592     -5.111      0.000    -5.5e+04   -2.45e+04
KitchenQual_n    7737.8815   2084.109      3.713      0.000    3648.411    1.18e+04
Functional_n    -6683.7505   1778.007     -3.759      0.000   -1.02e+04   -3194.918
Fireplaces_n      1.53e+04   2263.052      6.763      0.000    1.09e+04    1.97e+04
GarageType_n    -3890.4405   1622.796     -2.397      0.017   -7074.715    -706.166
GarageFinish_n   2761.5645   1651.008      1.673      0.095    -478.068    6001.197
GarageCars_n     6090.2112   1621.893      3.755      0.000    2907.708    9272.715
PavedDrive_n    -1982.0175   3627.817     -0.546      0.585   -9100.575    5136.540
PoolArea_n      -2.964e+04   4429.253     -6.693      0.000   -3.83e+04    -2.1e+04
SaleCondition_n  1158.8683   1600.297      0.724      0.469   -1981.259    4298.995
Neighborhood_n   -968.5267    209.757     -4.617      0.000   -1380.115    -556.938
Exterior1st_n     -88.5290    513.689     -0.172      0.863   -1096.497     919.439
YearBuilt         615.9980     82.732      7.446      0.000     453.660     778.336
YearRemodAdd      544.1157     84.149      6.466      0.000     378.998     709.234
GarageYrBlt       -41.7465     94.462     -0.442      0.659    -227.101     143.608
TotalBsmtSF        18.6354      7.747      2.406      0.016       3.435      33.836
1stFlrSF            2.9726      4.210      0.706      0.480      -5.288      11.233
1stFlrSF            2.9726      4.210      0.706      0.480      -5.288      11.233
GrLivArea          68.1930      5.054     13.493      0.000      58.276      78.110
TotRmsAbvGrd     3098.5258   1456.013      2.128      0.034     241.515    5955.537
GarageArea         52.3031      9.536      5.485      0.000      33.592      71.015
MiscVal             8.3630      7.201      1.161      0.246      -5.767      22.493
==============================================================================
Omnibus:                      577.099   Durbin-Watson:                   1.913
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            60988.758
Skew:                          -1.462   Prob(JB):                         0.00
Kurtosis:                      39.461   Cond. No.                     1.01e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is  2e-22. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""